name: Publish Package

on:
   push:
     branches:
       - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
